site_name: Портфолио | Анна Барыкина

nav:
  - Главная страница: index.md
  - Обо мне: author.md
  - Лабораторные работы: labs_list.md

theme:
  name: dracula
  language: ru  

extra_css:
  - stylesheets/extra.css

plugins:
  - search

docs_dir: 'src/docs'